// Code generated by MockGen. DO NOT EDIT.
// Source: /home/nakamuraitsuki/program/Maximum/Infra/Maximum-Infra-hands-on/backend/internal/usecase/roomUsecase.go
//
// Generated by this command:
//
//	mockgen -source=/home/nakamuraitsuki/program/Maximum/Infra/Maximum-Infra-hands-on/backend/internal/usecase/roomUsecase.go -destination=test/mocks/usecase/roomUsecase_mock.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	reflect "reflect"

	entity "example.com/infrahandson/internal/domain/entity"
	usecase "example.com/infrahandson/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomUseCaseInterface is a mock of RoomUseCaseInterface interface.
type MockRoomUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRoomUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockRoomUseCaseInterfaceMockRecorder is the mock recorder for MockRoomUseCaseInterface.
type MockRoomUseCaseInterfaceMockRecorder struct {
	mock *MockRoomUseCaseInterface
}

// NewMockRoomUseCaseInterface creates a new mock instance.
func NewMockRoomUseCaseInterface(ctrl *gomock.Controller) *MockRoomUseCaseInterface {
	mock := &MockRoomUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockRoomUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomUseCaseInterface) EXPECT() *MockRoomUseCaseInterfaceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRoomUseCaseInterface) CreateRoom(req usecase.CreateRoomRequest) (usecase.CreateRoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", req)
	ret0, _ := ret[0].(usecase.CreateRoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomUseCaseInterfaceMockRecorder) CreateRoom(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).CreateRoom), req)
}

// DeleteRoom mocks base method.
func (m *MockRoomUseCaseInterface) DeleteRoom(req usecase.DeleteRoomRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockRoomUseCaseInterfaceMockRecorder) DeleteRoom(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).DeleteRoom), req)
}

// GetAllRooms mocks base method.
func (m *MockRoomUseCaseInterface) GetAllRooms() ([]*entity.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRooms")
	ret0, _ := ret[0].([]*entity.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRooms indicates an expected call of GetAllRooms.
func (mr *MockRoomUseCaseInterfaceMockRecorder) GetAllRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRooms", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).GetAllRooms))
}

// GetRoomByID mocks base method.
func (m *MockRoomUseCaseInterface) GetRoomByID(params usecase.GetRoomByIDParams) (usecase.GetRoomByIDResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", params)
	ret0, _ := ret[0].(usecase.GetRoomByIDResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockRoomUseCaseInterfaceMockRecorder) GetRoomByID(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).GetRoomByID), params)
}

// GetUsersInRoom mocks base method.
func (m *MockRoomUseCaseInterface) GetUsersInRoom(req usecase.GetUsersInRoomRequest) (usecase.GetUsersInRoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersInRoom", req)
	ret0, _ := ret[0].(usecase.GetUsersInRoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersInRoom indicates an expected call of GetUsersInRoom.
func (mr *MockRoomUseCaseInterfaceMockRecorder) GetUsersInRoom(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersInRoom", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).GetUsersInRoom), req)
}

// JoinRoom mocks base method.
func (m *MockRoomUseCaseInterface) JoinRoom(req usecase.JoinRoomRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockRoomUseCaseInterfaceMockRecorder) JoinRoom(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).JoinRoom), req)
}

// LeaveRoom mocks base method.
func (m *MockRoomUseCaseInterface) LeaveRoom(req usecase.LeaveRoomRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveRoom", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveRoom indicates an expected call of LeaveRoom.
func (mr *MockRoomUseCaseInterfaceMockRecorder) LeaveRoom(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveRoom", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).LeaveRoom), req)
}

// SearchRoom mocks base method.
func (m *MockRoomUseCaseInterface) SearchRoom(req usecase.SearchRoomRequest) (usecase.SearchRoomResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchRoom", req)
	ret0, _ := ret[0].(usecase.SearchRoomResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchRoom indicates an expected call of SearchRoom.
func (mr *MockRoomUseCaseInterfaceMockRecorder) SearchRoom(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchRoom", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).SearchRoom), req)
}

// UpdateRoomName mocks base method.
func (m *MockRoomUseCaseInterface) UpdateRoomName(req usecase.UpdateRoomNameRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomName", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomName indicates an expected call of UpdateRoomName.
func (mr *MockRoomUseCaseInterfaceMockRecorder) UpdateRoomName(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomName", reflect.TypeOf((*MockRoomUseCaseInterface)(nil).UpdateRoomName), req)
}
