// Code generated by MockGen. DO NOT EDIT.
// Source: /home/nakamuraitsuki/program/Maximum/Infra/Maximum-Infra-hands-on/backend/internal/usecase/userUsecase.go
//
// Generated by this command:
//
//	mockgen -source=/home/nakamuraitsuki/program/Maximum/Infra/Maximum-Infra-hands-on/backend/internal/usecase/userUsecase.go -destination=test/mocks/usecase/userUsecase_mock.go
//

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	entity "example.com/infrahandson/internal/domain/entity"
	service "example.com/infrahandson/internal/domain/service"
	usecase "example.com/infrahandson/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockUserUseCaseInterface is a mock of UserUseCaseInterface interface.
type MockUserUseCaseInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserUseCaseInterfaceMockRecorder
	isgomock struct{}
}

// MockUserUseCaseInterfaceMockRecorder is the mock recorder for MockUserUseCaseInterface.
type MockUserUseCaseInterfaceMockRecorder struct {
	mock *MockUserUseCaseInterface
}

// NewMockUserUseCaseInterface creates a new mock instance.
func NewMockUserUseCaseInterface(ctrl *gomock.Controller) *MockUserUseCaseInterface {
	mock := &MockUserUseCaseInterface{ctrl: ctrl}
	mock.recorder = &MockUserUseCaseInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUseCaseInterface) EXPECT() *MockUserUseCaseInterfaceMockRecorder {
	return m.recorder
}

// AuthenticateUser mocks base method.
func (m *MockUserUseCaseInterface) AuthenticateUser(ctx context.Context, req usecase.AuthenticateUserRequest) (usecase.AuthenticateUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthenticateUser", ctx, req)
	ret0, _ := ret[0].(usecase.AuthenticateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthenticateUser indicates an expected call of AuthenticateUser.
func (mr *MockUserUseCaseInterfaceMockRecorder) AuthenticateUser(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthenticateUser", reflect.TypeOf((*MockUserUseCaseInterface)(nil).AuthenticateUser), ctx, req)
}

// GetUserByID mocks base method.
func (m *MockUserUseCaseInterface) GetUserByID(ctx context.Context, id entity.UserID) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserUseCaseInterfaceMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserUseCaseInterface)(nil).GetUserByID), ctx, id)
}

// GetUserIcon mocks base method.
func (m *MockUserUseCaseInterface) GetUserIcon(ctx context.Context, id entity.UserID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIcon", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIcon indicates an expected call of GetUserIcon.
func (mr *MockUserUseCaseInterfaceMockRecorder) GetUserIcon(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIcon", reflect.TypeOf((*MockUserUseCaseInterface)(nil).GetUserIcon), ctx, id)
}

// SaveUserIcon mocks base method.
func (m *MockUserUseCaseInterface) SaveUserIcon(ctx context.Context, icon service.IconData, id entity.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserIcon", ctx, icon, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserIcon indicates an expected call of SaveUserIcon.
func (mr *MockUserUseCaseInterfaceMockRecorder) SaveUserIcon(ctx, icon, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserIcon", reflect.TypeOf((*MockUserUseCaseInterface)(nil).SaveUserIcon), ctx, icon, id)
}

// SignUp mocks base method.
func (m *MockUserUseCaseInterface) SignUp(ctx context.Context, req usecase.SignUpRequest) (usecase.SignUpResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, req)
	ret0, _ := ret[0].(usecase.SignUpResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockUserUseCaseInterfaceMockRecorder) SignUp(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockUserUseCaseInterface)(nil).SignUp), ctx, req)
}
