// Code generated by MockGen. DO NOT EDIT.
// Source: /home/nakamuraitsuki/program/Maximum/Infra/Maximum-Infra-hands-on/backend/internal/interface/factory/websocket_connection_factory.go
//
// Generated by this command:
//
//	mockgen -source=/home/nakamuraitsuki/program/Maximum/Infra/Maximum-Infra-hands-on/backend/internal/interface/factory/websocket_connection_factory.go -destination=mocks/interface/factory/websocket_connection_factory_mock.go
//

// Package mock_factory is a generated GoMock package.
package mock_factory

import (
	reflect "reflect"

	service "example.com/webrtc-practice/internal/domain/service"
	adapter "example.com/webrtc-practice/internal/interface/adapter"
	gomock "go.uber.org/mock/gomock"
)

// MockWebSocketConnectionFactory is a mock of WebSocketConnectionFactory interface.
type MockWebSocketConnectionFactory struct {
	ctrl     *gomock.Controller
	recorder *MockWebSocketConnectionFactoryMockRecorder
	isgomock struct{}
}

// MockWebSocketConnectionFactoryMockRecorder is the mock recorder for MockWebSocketConnectionFactory.
type MockWebSocketConnectionFactoryMockRecorder struct {
	mock *MockWebSocketConnectionFactory
}

// NewMockWebSocketConnectionFactory creates a new mock instance.
func NewMockWebSocketConnectionFactory(ctrl *gomock.Controller) *MockWebSocketConnectionFactory {
	mock := &MockWebSocketConnectionFactory{ctrl: ctrl}
	mock.recorder = &MockWebSocketConnectionFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebSocketConnectionFactory) EXPECT() *MockWebSocketConnectionFactoryMockRecorder {
	return m.recorder
}

// CreateWebSocketConnection mocks base method.
func (m *MockWebSocketConnectionFactory) CreateWebSocketConnection(conn adapter.ConnAdapter) (service.WebSocketConnection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebSocketConnection", conn)
	ret0, _ := ret[0].(service.WebSocketConnection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebSocketConnection indicates an expected call of CreateWebSocketConnection.
func (mr *MockWebSocketConnectionFactoryMockRecorder) CreateWebSocketConnection(conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebSocketConnection", reflect.TypeOf((*MockWebSocketConnectionFactory)(nil).CreateWebSocketConnection), conn)
}
